import React from 'react'
import Head from 'next/head';
import Contact from '../components/Contact'
import Intro from '../components/Intro'

const contact = () => {
  return (
    <div>
        <Head>
          <title>Contact Page</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <Intro 
          heading='Contact' 
          message='Submit the form below for more work and quotes.'
          buttonPath='#form'
          buttonMessage='Go'
         />
        <Contact path='form' />
    </div>
  )
}

export default contact