import React from "react";
import Head from "next/head";
import Intro from "../components/Intro";
import Slider from "@/components/Slider";

const jobs = [
  {
    year: "Sep 2021 – Sep 2022",
    title: "Programmer",
    text: [
      "Designed and developed front-end pages using VueJS, JavaScript, HTML5, and CSS",
      "Synchronized middleware functions in back-end applications using Express",
      "Created new stored procedures in MS SQL server to enhance the project performance",
      "Established API connections with the marketplaces of Shopify and Wix",
      "Created login page with Oauth 2.0 to authorize users",
      "Implemented the version control, collaboration, and code management using tools such as Git and Bitbucket",
    ],
    company: "Yusen Logistics (Hong Kong) Limited",
    address: "Hong Kong, China",
  },
  {
    year: "Feb 2020 – May 2020",
    title: "STEM Project Develoepr, Intern",
    text: [
      "Established the project proposal with system architecture, block diagrams, and operation principles",
      "Developed the customed Python Libraries applications for Firebase, ThingSpeak, and IFTTT using PyCharm",
      "Built the corresponding RESTful API functions with reusable codes",
      "Handled the HTTP requests and response by using Python Requests Library",
      "Implemented production migrations, monitoring, troubleshooting, tuning",
      "Provided the technical documents for the use of Python Libraires",
    ],
    company: "Winstars Enterprise HK Limited",
    address: "Hong Kong, China",
  },
  {
    year: "Apr 2018 – Aug 2018",
    title: "Contract Junior Programmer",
    text: [
      "Developed and maintain Java applications using IntelliJ IDEA",
      "Used Spring MVC to build and deploy web applications",
      "Containerized applications using Docker",
      "Used Bitbucket for version control, code management, and collaboration",
      "Wrote and executed unit tests to ensure code quality using Junit",
      "Collaborated with team members to resolve technical issues and bugs",
    ],
    company: "Taylor Coulter Limited",
    address: "Hong Kong, China",
  },
  {
    year: "July 2016 – Aug 2016",
    title: "Assistant Officer",
    text: [
      "Provided clerical support such as data input and filing, quality checking",
      "Worked on data cleansing, input and update data in internal system",
      "Maintained accurate records and thorough documentation",
      "Assisted in any ad-hoc assignments or special projects",
    ],
    company: "Principal Trust Company (Asia) Limited",
    address: "Hong Kong, China",
  },
];

const experience = () => {
  return (
    <div>
      <Head>
        <title>Experience Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Intro
        heading="Summary"
        message="Highly motivated and self-driven developer with bachelor’s degree in Information
        Engineering. Solid understanding with JavaScript, HTML, and CSS. Familiar with
        developing java-based backend system and having experience to develop Spring
        Boot microservice system and Spring MVC application. Passion, self-motivated,
        and committed to becoming a professional full stack developer."
        buttonPath="#details"
        buttonMessage="More"
      />
      <div className="col d-flex flex-column flex-md-row justify-content-around align-items-center"></div>
      <Slider path="details" title="Details" itemsArray={jobs} />
    </div>
  );
};

export default experience;
