import React from 'react'
import Head from 'next/head';
import Intro from '../components/Intro';
import LoadingPage from '@/components/LoadingPage';


const project = () => {
  return (
    <LoadingPage content={
      <div>
        <Head>
          <title>Project Page</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <Intro 
          heading='Description' 
          message='The projects will be uploaded soon...'
          // buttonPath='#details'
          // buttonMessage='Check'
        />
        <div className="col d-flex flex-column flex-md-row justify-content-around align-items-center">
        </div>
        {/* <Slider path='details' title='Details' itemsArray={jobs} /> */}
      </div>
    }/>
  )
}

export default project

// import React from 'react'

// const project = () => {
//   return (
//     <div>project</div>
//   )
// }

// export default project